server:
  port: 8081
  servlet:
    context-path: /library
spring:
  application:
    name: Library Management System
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
      repositories:
        enabled: true
    jpa:
      repositories:
        enabled: true
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    url: jdbc:postgresql://localhost:5432/eshop
    username: eshop
    password: eshop@@@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    open-in-view: false   # Significant attribute. Dont open transaction at controller entry point
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
debug: true
