spring:
  jms:
    template:
      delivery-mode: persistent
    pub-sub-domain: true
    cache:
      enabled: false
  activemq:
    in-memory: false
  application:
    name: Consumer
server:
  port: 8181